#!/usr/bin/env node
// scripts/consent-gate.mjs — make every analytics tag inert until consent.
//
// Run:  npm run consent:gate          (rewrites the pages)
//       npm run consent:check         (verifies, changes nothing, exits 1 on a gap)
//
// Audit point 7: Google Analytics, PostHog and Sentry session replay all
// started on page load across 44 pages, before anybody agreed to anything, and
// there was no banner. This is the mechanical half of the fix - editing 44
// files by hand is how one gets missed, and a missed one is a page that still
// tracks silently.
//
// WHAT IT DOES
//
// An analytics <script> becomes <script type="text/plain" data-consent="analytics">.
// No browser executes that. js/consent.js turns them back into real scripts
// once the visitor accepts, and never otherwise. It also injects the
// js/consent.js tag itself, first, synchronously - Consent Mode has to be
// declared before any tag reads it.
//
// It is idempotent: a page already gated is left alone, so it can run again
// after new pages are generated by scripts/generate-suburb-pages.mjs.
//
// WHAT IT DELIBERATELY DOES NOT TOUCH
//
// <script type="application/ld+json"> (structured data for Google, no
// tracking), the service worker, Stripe, Leaflet, and every application
// script. Only the four analytics vendors below.

import fs from 'node:fs';
import { VENDOR_USES } from './lib/consent-vendors.mjs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.join(path.dirname(fileURLToPath(import.meta.url)), '..');
const checkOnly = process.argv.includes('--check');

const CONSENT_TAG = '<script src="/js/consent.js"></script>';

// Each entry: how to recognise an analytics script tag. `src` matches the
// loader; `body` matches an inline block by something only that vendor writes.
const VENDORS = [
  {
    name: 'Google Analytics',
    src: /googletagmanager\.com/,
    body: /gtag\(\s*['"](?:js|config)['"]/,
  },
  { name: 'Sentry', src: /sentry-cdn\.com/, body: /Sentry\.onLoad\s*\(/ },
  { name: 'PostHog', src: /posthog/i, body: /posthog\.init\s*\(/ },
  { name: 'Meta Pixel', src: /connect\.facebook\.net/, body: /fbq\(\s*['"]init['"]/ },
];

// Matches one <script ...>...</script>, non-greedy. Good enough here because
// these are hand-written head blocks, not arbitrary HTML with "</script>"
// inside a string.
const SCRIPT_RE = /<script\b([^>]*)>([\s\S]*?)<\/script>/gi;

function isAnalytics(attrs, body) {
  // Structured data is not analytics and must keep working.
  if (/type\s*=\s*["']application\/ld\+json["']/i.test(attrs)) return null;
  for (const v of VENDORS) {
    const srcMatch = /\bsrc\s*=\s*["']([^"']+)["']/i.exec(attrs);
    if (srcMatch && v.src.test(srcMatch[1])) return v.name;
    if (!srcMatch && v.body.test(body)) return v.name;
  }
  return null;
}

function gate(html) {
  let found = 0;
  let alreadyGated = 0;

  const out = html.replace(SCRIPT_RE, (whole, attrs, body) => {
    if (/data-consent\s*=/i.test(attrs)) {
      alreadyGated++;
      return whole;
    }
    const vendor = isAnalytics(attrs, body);
    if (!vendor) return whole;
    found++;
    // Drop any existing type= (gtag's loader has none; be safe anyway) and add
    // the inert type plus the marker consent.js looks for.
    const cleaned = attrs.replace(/\s*\btype\s*=\s*["'][^"']*["']/i, '');
    return `<script type="text/plain" data-consent="analytics"${cleaned}>${body}</script>`;
  });

  return { out, found, alreadyGated };
}

function withConsentTag(html) {
  if (html.includes('/js/consent.js')) return { html, injected: false };
  // Immediately before the first gated tag, so Consent Mode's default is set
  // before anything could read it.
  const i = html.search(/<script[^>]*data-consent="analytics"/i);
  if (i === -1) return { html, injected: false };
  const indent = /(^|\n)([ \t]*)$/.exec(html.slice(0, i))?.[2] ?? '';
  return { html: html.slice(0, i) + CONSENT_TAG + '\n' + indent + html.slice(i), injected: true };
}

function htmlFiles(dir, acc = []) {
  for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
    if (e.name === 'node_modules' || e.name === '.git' || e.name === 'tests') continue;
    const p = path.join(dir, e.name);
    if (e.isDirectory()) htmlFiles(p, acc);
    else if (e.name.endsWith('.html')) acc.push(p);
  }
  return acc;
}

const files = htmlFiles(root).sort();
let changed = 0;
const ungated = [];
let totalTags = 0;

for (const file of files) {
  const rel = path.relative(root, file).replace(/\\/g, '/');
  const original = fs.readFileSync(file, 'utf8');
  const { out, found, alreadyGated } = gate(original);
  totalTags += found + alreadyGated;

  if (!found && !alreadyGated) continue; // no analytics on this page at all

  const { html: final, injected } = withConsentTag(out);

  if (final !== original) {
    if (checkOnly) {
      ungated.push(`${rel} (${found} tag(s) still live${injected ? ', no consent.js' : ''})`);
    } else {
      fs.writeFileSync(file, final);
      changed++;
      console.log(`  gated ${rel}: ${found} tag(s)${injected ? ' + consent.js' : ''}`);
    }
  } else if (checkOnly && !final.includes('/js/consent.js')) {
    ungated.push(`${rel} (gated tags but consent.js missing)`);
  }
}

// ── The half that lived outside the HTML ────────────────────────────────────
// Everything above reads TAGS. It found nothing wrong on 2026-08-31 while the
// landing page was dead in every browser that had not accepted cookies.
//
// What happened: d5bb2f8 extracted landing.html's 15 inline <script> blocks
// into js/landing-inline.js for page weight. Two of those blocks were vendor
// bootstraps that this script had gated. Out of the HTML, they were invisible
// to it - so the gate came off, while the loader <script src> they depend on
// stayed gated in the page.
//
//   - Sentry: the loader never ran, so `Sentry` did not exist, and
//     `Sentry.onLoad()` on line 9 of a file that is ONE top-level scope threw
//     ReferenceError. Every listener defined below it - Book a Service, View
//     Services, My Account, the mechanics carousel - was never attached. The
//     landing page had no working buttons for anyone who declined cookies,
//     used Firefox with Enhanced Tracking Protection, or ran a blocker.
//   - Google Analytics: gtag() defines itself, so it threw nothing. It just
//     configured GA on every view without asking, which is the exact thing
//     this file exists to prevent.
//
// So: a JS file the page loads UNCONDITIONALLY may not touch a vendor global
// that only exists after consent. Only the two that bit are listed - a vendor
// whose snippet defines its own stub (PostHog) is not in this class, and
// guessing at more would cost false positives, which is how a check stops
// being read.

const leaks = [];
for (const file of files) {
  const rel = path.relative(root, file);
  const html = fs.readFileSync(file, 'utf8');
  // Local <script src> with no data-consent: it runs on every view, always.
  for (const m of html.matchAll(/<script\b([^>]*)\bsrc="([^"]+)"([^>]*)>/g)) {
    const attrs = m[1] + m[3];
    if (/data-consent/.test(attrs)) continue;
    const src = m[2];
    if (/^https?:|^\/\//.test(src)) continue; // third-party, not ours to read
    const jsPath = path.join(root, src.replace(/^\//, '').split('?')[0]);
    if (!fs.existsSync(jsPath)) continue;
    const js = fs.readFileSync(jsPath, 'utf8');
    for (const v of VENDOR_USES) {
      if (v.re.test(js)) {
        leaks.push({ page: rel, js: path.relative(root, jsPath), vendor: v.name, why: v.why });
      }
    }
  }
}

if (checkOnly && leaks.length) {
  console.error(`\nconsent-check: ${leaks.length} ungated script(s) use a consent-gated vendor\n`);
  for (const l of new Map(leaks.map((x) => [x.js + x.vendor, x])).values()) {
    console.error(`  x ${l.js} uses ${l.vendor} - loaded unconditionally by ${l.page}`);
    console.error(`      ${l.why}`);
  }
  console.error(
    '\n  fix: move that bootstrap back into the page as\n' +
      '       <script type="text/plain" data-consent="analytics">, the way index.html\n' +
      '       carries it. Do not just guard it - a guard leaves the vendor dead\n' +
      '       forever, because this file only runs once, before consent.\n'
  );
  process.exit(1);
}

if (checkOnly) {
  if (ungated.length) {
    console.error(`\nconsent-check: ${ungated.length} page(s) run analytics before consent\n`);
    for (const u of ungated) console.error(`  x ${u}`);
    console.error('\nRun: npm run consent:gate\n');
    process.exit(1);
  }
  console.log(
    `consent-check: OK - ${totalTags} analytics tag(s) gated across ${files.length} pages.`
  );
} else {
  console.log(`\nconsent-gate: ${changed} page(s) rewritten, ${totalTags} analytics tag(s) total.`);
}
